#!/bin/bash
#PBS -P 11004323
#PBS -N analyze_swimmers
#PBS -q normal
#PBS -j oe                                      
#PBS -o run_swimmers_array_log_Dr_1/radial_distribution.log                        
#PBS -l select=1:ncpus=32:mem=128gb
#PBS -l walltime=02:00:00

cd $PBS_O_WORKDIR

# Load the Conda module
module load miniforge3

# Activate the environment
source activate dip_swim_env

# Set threads for freud's multi-threaded C++ backend
export OMP_NUM_THREADS=1                         

# ---------------------------------------------------------
# Execution
# ---------------------------------------------------------
echo "Analysis run started at: $(date)"
echo "Running on host: $HOSTNAME"
echo "---------------------------------------------------"

# Navigate to high-capacity scartch directory
cd /scratch/users/nus/e0028670/run_swimmers_array_data_Dr_1

# Execute the python script
python $PBS_O_WORKDIR/radial_distribution.py

echo "---------------------------------------------------"
echo "Analysis run finished at: $(date)"
